package cscscheduler;

// Generated Mar 20, 2013 4:04:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * Advisors generated by hbm2java
 */
public class Advisors implements java.io.Serializable {

	private String accessId;
	private String firstName;
	private String lastName;
	private String advisorEmail;
	private String phone;
	private String location;

	public Advisors() {
	}

	public Advisors(String accessId) {
		this.accessId = accessId;
	}

	public Advisors(String accessId, String firstName, String lastName,
			String advisorEmail, String phone, String location) {
		this.accessId = accessId;
		this.firstName = firstName;
		this.lastName = lastName;
		this.advisorEmail = advisorEmail;
		this.phone = phone;
		this.location = location;
	}

	public String getAccessId() {
		return this.accessId;
	}

	public void setAccessId(String accessId) {
		this.accessId = accessId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAdvisorEmail() {
		return this.advisorEmail;
	}

	public void setAdvisorEmail(String advisorEmail) {
		this.advisorEmail = advisorEmail;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

}
