package cscscheduler;

// Generated Mar 20, 2013 4:04:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * AdvisorAvailability generated by hbm2java
 */
public class AdvisorAvailability implements java.io.Serializable {

	private AdvisorAvailabilityId id;

	public AdvisorAvailability() {
	}

	public AdvisorAvailability(AdvisorAvailabilityId id) {
		this.id = id;
	}

	public AdvisorAvailabilityId getId() {
		return this.id;
	}

	public void setId(AdvisorAvailabilityId id) {
		this.id = id;
	}

}
