package cscscheduler;

// Generated Mar 20, 2013 4:04:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * AdvisorAvailabilityId generated by hbm2java
 */
public class AdvisorAvailabilityId implements java.io.Serializable {

	private String advisorAccessId;
	private String weekday;
	private int startTime;
	private int endTime;

	public AdvisorAvailabilityId() {
	}

	public AdvisorAvailabilityId(String advisorAccessId, String weekday,
			int startTime, int endTime) {
		this.advisorAccessId = advisorAccessId;
		this.weekday = weekday;
		this.startTime = startTime;
		this.endTime = endTime;
	}

	public String getAdvisorAccessId() {
		return this.advisorAccessId;
	}

	public void setAdvisorAccessId(String advisorAccessId) {
		this.advisorAccessId = advisorAccessId;
	}

	public String getWeekday() {
		return this.weekday;
	}

	public void setWeekday(String weekday) {
		this.weekday = weekday;
	}

	public int getStartTime() {
		return this.startTime;
	}

	public void setStartTime(int startTime) {
		this.startTime = startTime;
	}

	public int getEndTime() {
		return this.endTime;
	}

	public void setEndTime(int endTime) {
		this.endTime = endTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AdvisorAvailabilityId))
			return false;
		AdvisorAvailabilityId castOther = (AdvisorAvailabilityId) other;

		return ((this.getAdvisorAccessId() == castOther.getAdvisorAccessId()) || (this
				.getAdvisorAccessId() != null
				&& castOther.getAdvisorAccessId() != null && this
				.getAdvisorAccessId().equals(castOther.getAdvisorAccessId())))
				&& ((this.getWeekday() == castOther.getWeekday()) || (this
						.getWeekday() != null && castOther.getWeekday() != null && this
						.getWeekday().equals(castOther.getWeekday())))
				&& (this.getStartTime() == castOther.getStartTime())
				&& (this.getEndTime() == castOther.getEndTime());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getAdvisorAccessId() == null ? 0 : this.getAdvisorAccessId()
						.hashCode());
		result = 37 * result
				+ (getWeekday() == null ? 0 : this.getWeekday().hashCode());
		result = 37 * result + this.getStartTime();
		result = 37 * result + this.getEndTime();
		return result;
	}

}
