package cscscheduler;

// Generated Mar 20, 2013 4:04:02 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * AppointmentsId generated by hbm2java
 */
public class AppointmentsId implements java.io.Serializable {

	private String studentEmail;
	private Date apptDate;

	public AppointmentsId() {
	}

	public AppointmentsId(String studentEmail, Date apptDate) {
		this.studentEmail = studentEmail;
		this.apptDate = apptDate;
	}

	public String getStudentEmail() {
		return this.studentEmail;
	}

	public void setStudentEmail(String studentEmail) {
		this.studentEmail = studentEmail;
	}

	public Date getApptDate() {
		return this.apptDate;
	}

	public void setApptDate(Date apptDate) {
		this.apptDate = apptDate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AppointmentsId))
			return false;
		AppointmentsId castOther = (AppointmentsId) other;

		return ((this.getStudentEmail() == castOther.getStudentEmail()) || (this
				.getStudentEmail() != null
				&& castOther.getStudentEmail() != null && this
				.getStudentEmail().equals(castOther.getStudentEmail())))
				&& ((this.getApptDate() == castOther.getApptDate()) || (this
						.getApptDate() != null
						&& castOther.getApptDate() != null && this
						.getApptDate().equals(castOther.getApptDate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getStudentEmail() == null ? 0 : this.getStudentEmail()
						.hashCode());
		result = 37 * result
				+ (getApptDate() == null ? 0 : this.getApptDate().hashCode());
		return result;
	}

}
