package cscscheduler;

// Generated Mar 20, 2013 4:04:02 PM by Hibernate Tools 3.4.0.CR1

/**
 * Test generated by hbm2java
 */
public class Test implements java.io.Serializable {

	private String accessId;

	public Test() {
	}

	public Test(String accessId) {
		this.accessId = accessId;
	}

	public String getAccessId() {
		return this.accessId;
	}

	public void setAccessId(String accessId) {
		this.accessId = accessId;
	}

}
